// Generated by scripts/scenes/build-frames.mjs — do not edit by hand.
// scenes[i] is the still the homepage holds on for data-stage section i;
// frames[i] is how many frames the transition from scene i to i+1 has.

export const SCENE_MANIFEST = {
  base: "/stack/scenes",
  scenes: ["hero","silicon","signal","data","atlas","kdv-website-services","371admin","new-z1on-lpg","tracky","coop-tracker","plantpal","now","contact"],
  frames: [42,42,42,42,42,42,42,42,42,42,42,42],
} as const;
