// Generated by scripts/scenes/build-frames.mjs — do not edit by hand.
// scenes[i] is the still the homepage holds on for data-stage section i;
// frames[i] is how many frames the transition from scene i to i+1 has.

export const SCENE_MANIFEST = {
  base: "/stack/scenes",
  scenes: ["hero","silicon","signal","data","atlas","kdv-website-services","371admin","new-z1on-lpg","tracky","coop-tracker","plantpal","now","contact"],
  /** Horizontal position of me in each scene; phone frames are already cropped around it. */
  focus: [0.6,0.7,0.3,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.32,0.3],
  /** Desktop-only rightward shift per scene, as a fraction of the screen width. */
  pan: [0.14,0,0,0,0,0,0,0,0,0,0,0,0],
  frames: [42,42,42,42,42,42,42,42,42,42,42,42],
} as const;
