// Turns the homepage transition clips into the scroll-scrubbed frame sequence.
//   node scripts/scenes/build-frames.mjs [clipsDir]
// Downloads any clip missing from clipsDir (default: .scene-clips, gitignored),
// then writes public/stack/scenes/{d,m}/SS-FFF.webp and components/stack/sceneManifest.ts.
// Sources are the 4K Topaz upscales (`uhd`), falling back to the 768p originals.
// d = desktop, the full 16:9 frame at 1600w. m = phones, a portrait crop
// 1152px tall that follows me from one scene's focus to the next.
// Clip N starts on scene N and ends on N+1.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("../../", import.meta.url).pathname;
const { base, focus, clips } = JSON.parse(readFileSync(join(root, "scripts/scenes/clips.json"), "utf8"));
const clipsDir = process.argv[2] ?? join(root, ".scene-clips");
const out = join(root, "public/stack/scenes");
// Every 3rd frame of a 24 fps, 5 s clip: 42 frames per transition.
const STEP = 3;
// Phone crop aspect (w / h): a little wider than a phone's scene area so
// slightly wider screens still fill it.
const PORTRAIT = 0.9;
const focusOf = (scene) => focus[scene] ?? focus._default;
const SIZES = [
  { dir: "d", quality: 72, vf: () => "scale=1600:-2:flags=lanczos" },
  {
    dir: "m",
    quality: 68,
    vf: (clip, frames) => {
      // Ease the crop from one scene's focus to the next, like the desktop framing does.
      const a = focusOf(clip.from);
      const b = focusOf(clip.to);
      const t = `(n/${frames - 1})`;
      const x = `(iw-ih*${PORTRAIT})*(${a}+(${b - a})*${t}*${t}*(3-2*${t}))`;
      return `crop=w=trunc(ih*${PORTRAIT}/2)*2:h=ih:x='${x}':y=0,scale=-2:1152:flags=lanczos`;
    },
  },
];

mkdirSync(clipsDir, { recursive: true });
rmSync(out, { recursive: true, force: true });
for (const s of SIZES) mkdirSync(join(out, s.dir), { recursive: true });

const counts = [];
clips.forEach((clip, i) => {
  const seg = String(i).padStart(2, "0");
  const src = join(clipsDir, clip.uhd ? `seg${seg}-uhd.mp4` : `seg${seg}.mp4`);
  if (!existsSync(src)) execFileSync("curl", ["-sSf", "-o", src, clip.uhd ?? `${base}${clip.id}.mp4`]);
  const total = Number(
    execFileSync("ffprobe", [
      "-v", "error", "-select_streams", "v", "-count_packets",
      "-show_entries", "stream=nb_read_packets", "-of", "csv=p=0", src,
    ]).toString().trim(),
  );
  for (const s of SIZES) {
    execFileSync("ffmpeg", [
      "-v", "error", "-y", "-i", src,
      "-vf", `${s.vf(clip, total)},select='not(mod(n\\,${STEP}))'`,
      "-vsync", "0", "-c:v", "libwebp", "-quality", String(s.quality),
      "-start_number", "0",
      join(out, s.dir, `${seg}-%03d.webp`),
    ]);
  }
  counts.push(readdirSync(join(out, "d")).filter((f) => f.startsWith(`${seg}-`)).length);
  console.log(`${seg} ${clip.from} → ${clip.to}: ${counts[i]} frames`);
});

const scenes = [clips[0].from, ...clips.map((c) => c.to)];
writeFileSync(
  join(root, "components/stack/sceneManifest.ts"),
  `// Generated by scripts/scenes/build-frames.mjs — do not edit by hand.
// scenes[i] is the still the homepage holds on for data-stage section i;
// frames[i] is how many frames the transition from scene i to i+1 has.

export const SCENE_MANIFEST = {
  base: "/stack/scenes",
  scenes: ${JSON.stringify(scenes)},
  /** Horizontal position of me in each scene; phone frames are already cropped around it. */
  focus: ${JSON.stringify(scenes.map(focusOf))},
  frames: ${JSON.stringify(counts)},
} as const;
`,
);
console.log(`${scenes.length} scenes, ${counts.reduce((a, b) => a + b, 0)} frames`);
