// Turns the homepage transition clips into the scroll-scrubbed frame sequence.
//   node scripts/scenes/build-frames.mjs [clipsDir]
// Downloads any clip missing from clipsDir (default: .scene-clips, gitignored),
// then writes public/stack/scenes/{d,m}/SS-FFF.webp (desktop 1280w, mobile 720w)
// and components/stack/sceneManifest.ts. Clip N starts on scene N and ends on N+1.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("../../", import.meta.url).pathname;
const { base, clips } = JSON.parse(readFileSync(join(root, "scripts/scenes/clips.json"), "utf8"));
const clipsDir = process.argv[2] ?? join(root, ".scene-clips");
const out = join(root, "public/stack/scenes");
// Every 3rd frame of a 24 fps, 5 s clip: 42 frames per transition.
const STEP = 3;
const SIZES = [
  { dir: "d", width: 1280, quality: 70 },
  { dir: "m", width: 720, quality: 66 },
];

mkdirSync(clipsDir, { recursive: true });
rmSync(out, { recursive: true, force: true });
for (const s of SIZES) mkdirSync(join(out, s.dir), { recursive: true });

const counts = [];
clips.forEach((clip, i) => {
  const seg = String(i).padStart(2, "0");
  const src = join(clipsDir, `seg${seg}.mp4`);
  if (!existsSync(src)) execFileSync("curl", ["-sSf", "-o", src, `${base}${clip.id}.mp4`]);
  for (const s of SIZES) {
    execFileSync("ffmpeg", [
      "-v", "error", "-y", "-i", src,
      "-vf", `select='not(mod(n\\,${STEP}))',scale=${s.width}:-2`,
      "-vsync", "0", "-c:v", "libwebp", "-quality", String(s.quality),
      "-start_number", "0",
      join(out, s.dir, `${seg}-%03d.webp`),
    ]);
  }
  counts.push(readdirSync(join(out, "d")).filter((f) => f.startsWith(`${seg}-`)).length);
  console.log(`${seg} ${clip.from} → ${clip.to}: ${counts[i]} frames`);
});

const scenes = [clips[0].from, ...clips.map((c) => c.to)];
writeFileSync(
  join(root, "components/stack/sceneManifest.ts"),
  `// Generated by scripts/scenes/build-frames.mjs — do not edit by hand.
// scenes[i] is the still the homepage holds on for data-stage section i;
// frames[i] is how many frames the transition from scene i to i+1 has.

export const SCENE_MANIFEST = {
  base: "/stack/scenes",
  scenes: ${JSON.stringify(scenes)},
  frames: ${JSON.stringify(counts)},
} as const;
`,
);
console.log(`${scenes.length} scenes, ${counts.reduce((a, b) => a + b, 0)} frames`);
