import {createRequire} from 'node:module';import fs from 'node:fs';const require=createRequire(import.meta.url);const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome',args:['--enable-unsafe-swiftshader']});const results={};
for(const mode of ['reduced','full']){const c=await b.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:2,reducedMotion:mode==='reduced'?'reduce':'no-preference'});const p=await c.newPage();await p.addInitScript(()=>{window.__metrics={longTasks:[],lcp:[]};new PerformanceObserver(l=>window.__metrics.longTasks.push(...l.getEntries().map(x=>x.duration))).observe({type:'longtask',buffered:true});new PerformanceObserver(l=>window.__metrics.lcp.push(...l.getEntries().map(x=>x.startTime))).observe({type:'largest-contentful-paint',buffered:true})});
await p.goto('http://localhost:3001');await p.waitForTimeout(3000);
results[mode]=await p.evaluate(()=>({navigation:performance.getEntriesByType('navigation').map(x=>({encoded:x.encodedBodySize,decoded:x.decodedBodySize,transfer:x.transferSize})),resources:performance.getEntriesByType('resource').filter(x=>x.name.startsWith(location.origin)).map(x=>({path:x.name.replace(location.origin,''),encoded:x.encodedBodySize,decoded:x.decodedBodySize,type:x.initiatorType})),metrics:window.__metrics,canvas:document.querySelector('canvas')?{width:document.querySelector('canvas').width,height:document.querySelector('canvas').height,cssWidth:document.querySelector('canvas').clientWidth}:null}));
if(mode==='full'){results.frames=await p.evaluate(()=>new Promise(resolve=>{const samples=[];const start=performance.now();let last=start;const max=document.documentElement.scrollHeight-innerHeight;const tick=now=>{samples.push(now-last);last=now;const t=Math.min(1,(now-start)/7000);scrollTo(0,max*t);if(t<1)requestAnimationFrame(tick);else{samples.sort((a,b)=>a-b);resolve({count:samples.length,p50:samples[Math.floor(samples.length*.5)],p95:samples[Math.floor(samples.length*.95)],max:samples.at(-1),longFrames:samples.filter(x=>x>50).length})}};requestAnimationFrame(tick)}));
await p.screenshot({path:'.artifacts/production-contact.png'});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(500);await p.screenshot({path:'.artifacts/production-desktop.png'});
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(400);await p.screenshot({path:'.artifacts/production-mobile.png'});
await p.getByRole('button',{name:'Switch to dark theme'}).click();await p.screenshot({path:'.artifacts/production-mobile-dark.png'});
}
await c.close();}
const sum=(a,filter)=>a.filter(filter).reduce((s,x)=>s+x.encoded,0);results.summary={initialHTML:results.reduced.navigation[0],fonts:sum(results.reduced.resources,x=>/woff/.test(x.path)),poster:sum(results.reduced.resources,x=>/demo-/.test(x.path)),baseJS:sum(results.reduced.resources,x=>/\.js/.test(x.path)),deferredJS:sum(results.full.resources,x=>/\.js/.test(x.path)&&!results.reduced.resources.some(r=>r.path===x.path)),textures:sum(results.full.resources,x=>/\/studio\/demo-/.test(x.path)),initialVideo:sum(results.full.resources,x=>/mp4/.test(x.path))};fs.writeFileSync('.artifacts/performance.json',JSON.stringify(results,null,2));console.log(JSON.stringify({summary:results.summary,frames:results.frames,metrics:results.full.metrics,canvas:results.full.canvas},null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
